export function buildWorkspaceDecisionMarkdown({
  decisionId,
  generatedAt,
  decision,
  analysis,
  workspace,
  suggestion,
}) {
  return [
    `# 工作区建议记录_${decisionId}`,
    "",
    `- 记录时间：${generatedAt}`,
    `- 决策：${decision === "accept" ? "采纳" : "不采纳"}`,
    `- 工作区：${workspace.workspaceTitle}`,
    `- 当前主方向：${workspace.linkedCardDirection || "待补充"}`,
    `- 内容主题：${analysis.fields.contentTopic}`,
    `- 内容目标：${analysis.fields.contentGoal}`,
    `- 首轮行动路径：${analysis.fields.primaryAssetActionLabel}`,
    "",
    "## 1. 工作区建议摘要",
    `- 总结：${suggestion.summary}`,
    `- 细化任务：${suggestion.refinedTask}`,
    `- 下一步建议：${suggestion.nextSuggestion}`,
    `- 后续推荐：${suggestion.recommendedFollowUp}`,
    "",
    "## 2. 可直接复用提示语",
    suggestion.draftPromptLine,
    "",
    "## 3. 风险检查",
    ...(suggestion.riskChecks || []).map((item) => `- ${item}`),
    "",
    "## 4. 人工补充",
    "- 这次为什么采纳/不采纳：",
    "- 这次工作区建议最有帮助的点：",
    "- 是否需要调整规则或字段：",
    "- 后续是否进入二轮优化：",
    "",
  ].join("\n");
}
