export function buildObsidianRefinementExplanationRecord({
  caseId,
  generatedDate,
  resultJsonPath,
  summaryMarkdown,
}) {
  return [
    `# 二轮解释验证_${generatedDate}_${caseId}`,
    "",
    "> 生成方式：代码侧 `run:case` + `export:obsidian-refinement-explanation` 自动生成草稿",
    `> 样例编号：${caseId}`,
    `> 生成日期：${generatedDate}`,
    `> 对应代码结果：${resultJsonPath}`,
    "> 文档状态：可继续编辑",
    "",
    "## 0. 使用说明",
    "- 这份记录专门用来验证二轮反馈映射是否合理。",
    "- 下面的“代码侧解释底稿”由端到端运行结果自动生成。",
    "- 你后续主要补的是：映射是否准确、关键词是否够用、是否需要规则修订。",
    "",
    "## 1. 代码侧解释底稿",
    "",
    summaryMarkdown.trim(),
    "",
    "## 2. 人工复核结论",
    "- review_case_id:",
    "- review_status: pending",
    "- explanation_status: pending",
    "- misclassified: pending",
    "- should_export_to_misclassified: pending",
    "- actual_issue:",
    "- suggested_keyword:",
    "- suggested_mapping_id:",
    "- suggested_positive_signal_id:",
    "- fallback_adjustment:",
    "",
    "- 映射是否合理：",
    "- 解释是否足够清楚：",
    "- 是否存在误判：",
    "- 是否需要加入误判样本导出：",
    "",
    "## 3. 规则调整建议",
    "- 建议新增关键词：",
    "- 建议修改映射 ID：",
    "- 建议新增保留信号：",
    "- 建议修改默认兜底：",
    "",
    "## 4. 后续动作",
    "- [ ] 更新反馈词映射",
    "- [ ] 更新误判样本记录",
    "- [ ] 更新规则修订任务单",
    "- [ ] 更新本次实验结论",
    "",
  ].join("\n");
}
