export function buildObsidianRuleRevisionTaskSheetRecord({
  generatedDate,
  sourceMarkdownPath,
  summaryMarkdown,
}) {
  return [
    `# 规则修订任务单_${generatedDate}`,
    "",
    "> 生成方式：代码侧 `report:rule-revision-task-sheet` + `export:obsidian-rule-revision-task-sheet` 自动生成草稿",
    `> 生成日期：${generatedDate}`,
    `> 对应代码报告：${sourceMarkdownPath}`,
    "> 文档状态：可继续编辑",
    "",
    "## 0. 使用说明",
    "- 这份任务单来自已确认需要导出的误判样本。",
    "- 下面的“代码侧任务底稿”已经把误判样本按建议映射、关键词、兜底策略做了初步归并。",
    "- 你后续主要补的是：真正要改哪条规则、谁来改、何时复跑验证。",
    "",
    "## 1. 代码侧任务底稿",
    "",
    summaryMarkdown.trim(),
    "",
    "## 2. 排期与责任",
    "- 本轮优先处理的任务 ID：",
    "- 负责人：",
    "- 预计复跑时间：",
    "",
    "## 3. 结果回填",
    "- [ ] 更新 feedback-catalog.json",
    "- [ ] 重新跑 case",
    "- [ ] 更新误判样本记录",
    "- [ ] 更新实验结论",
    "",
  ].join("\n");
}
