export function buildObsidianRefinementExplanationSummaryRecord({
  generatedDate,
  sourceMarkdownPath,
  summaryMarkdown,
}) {
  return [
    `# 二轮解释验证汇总_${generatedDate}`,
    "",
    "> 生成方式：代码侧 `report:refinement-explanations` + `export:obsidian-refinement-explanations` 自动生成草稿",
    `> 生成日期：${generatedDate}`,
    `> 对应代码报告：${sourceMarkdownPath}`,
    "> 文档状态：可继续编辑",
    "",
    "## 0. 使用说明",
    "- 这份汇总用于判断哪些反馈映射最值得优先复核。",
    "- 下面的“代码侧汇总底稿”来自当前已运行的 case-runs 结果。",
    "- 你后续重点补：哪些映射需要修、哪些只是样本太少、哪些要进误判样本。",
    "",
    "## 1. 代码侧汇总底稿",
    "",
    summaryMarkdown.trim(),
    "",
    "## 2. 复核结论",
    "- 当前最需要优先检查的映射 ID：",
    "- 走兜底规则最多的原因：",
    "- 哪类反馈词最缺：",
    "",
    "## 3. 规则修订动作",
    "- [ ] 更新 feedback-catalog.json",
    "- [ ] 回填误判样本",
    "- [ ] 更新规则修订任务单",
    "- [ ] 更新本次实验结论",
    "",
  ].join("\n");
}
