import { compactText } from "../../shared/text.js";

export function buildPlatformCasePlaceholder({
  platformCaseId,
  platform = "抖音",
  contentTopic = "",
  sourceLink = "",
}) {
  const normalizedPlatformCaseId = compactText(platformCaseId);
  const normalizedPlatform = compactText(platform) || "抖音";
  const normalizedContentTopic = compactText(contentTopic);
  const normalizedSourceLink = compactText(sourceLink);

  if (!normalizedPlatformCaseId) {
    throw new Error('Platform case placeholder requires "platformCaseId".');
  }

  return [
    "# 平台案例占位",
    "",
    "> 状态：待回填真实样本",
    "> 使用方式：拿到真实平台封面截图/链接后，优先按 `平台案例标注模板_v0.2.md` 回填，再按真实主题重命名文件。",
    `> 平台案例编号：${normalizedPlatformCaseId}`,
    "",
    "## 0. 基础信息",
    `- case_id：${normalizedPlatformCaseId}`,
    `- source_platform：${normalizedPlatform}`,
    "- creator_type：",
    "- creator_stage_guess：",
    `- content_topic：${normalizedContentTopic}`,
    "- content_goal_guess：",
    "- content_type_primary：",
    "- content_type_secondary：",
    "- capture_date：",
    `- link_or_asset_path：${normalizedSourceLink}`,
    "",
    "## 1. 客观封面事实",
    "- subject_description：",
    "- visual_focus：",
    "- composition_features：",
    "- color_mood_features：",
    "- cover_copy_features：",
    "- title_cover_relationship：",
    "",
    "## 2. 点击机制判断",
    "- click_driver_primary：",
    "- click_driver_secondary：",
    "- has_clear_result：",
    "- has_contrast：",
    "- has_curiosity_gap：",
    "- requires_clarity：",
    "- requires_trust：",
    "",
    "## 3. 素材与视觉支撑判断",
    "- asset_subject_strength：",
    "- asset_visual_tension：",
    "- asset_aesthetic_quality：",
    "- asset_information_density：",
    "",
    "## 4. 封面方向映射",
    "- direction_type_primary：",
    "- direction_type_secondary：",
    "- direction_fit_reason：",
    "- direction_risk：",
    "- direction_boundary：",
    "",
    "## 5. 可借用策略拆解",
    "- visual_strategy：",
    "- copy_strategy：",
    "- composition_strategy：",
    "- expected_click_reason：",
    "",
    "## 6. 平台化特征",
    "- platform_native_signal：",
    "- platform_expression_habit：",
    "- why_it_feels_clickable_on_platform：",
    "",
    "## 7. 反馈词提炼",
    "- likely_positive_feedback：",
    "- likely_negative_feedback：",
    "- feedback_keywords_extract：",
    "- possible_adjustment_direction：",
    "",
    "## 8. 产品规则库转译",
    "- which_rule_it_strengthens：",
    "- which_user_scenario_it_fits：",
    "- whether_it_requires_rule_revision：",
    "- revision_note_if_any：",
    "",
    "## 9. 快速结论",
    "- one_sentence_summary：",
    "- reusable_level：",
    "- reuse_warning：",
    "",
  ].join("\n");
}
