export function buildObsidianCaseProgressRecord({
  generatedDate,
  sourceMarkdownPath,
  progressMarkdown,
}) {
  return [
    `# 案例进度状态_${generatedDate}`,
    "",
    "> 生成方式：代码侧 `report:case-progress` + `export:obsidian-progress` 自动生成草稿",
    `> 生成日期：${generatedDate}`,
    `> 对应代码报告：${sourceMarkdownPath}`,
    "> 文档状态：可继续编辑",
    "",
    "## 0. 使用说明",
    "- 这是一份代码侧自动生成的案例进度状态草稿。",
    "- 下面的“代码侧状态底稿”来自当前 case-progress 报告。",
    "- 你后续应继续补：阶段判断、阻塞点、下一批动作。",
    "",
    "## 1. 代码侧状态底稿",
    "",
    progressMarkdown.trim(),
    "",
    "## 2. 阶段判断",
    "- 当前最关键的推进断点：",
    "- 哪一层最容易积压：",
    "- 哪个环节已经比较顺：",
    "",
    "## 3. 下一批动作",
    "- [ ] 下一条要推进的真实案例：",
    "- [ ] 下一次要跑的命令：",
    "- [ ] 需要补的规则或文档：",
    "",
  ].join("\n");
}
