export function buildObsidianRealCaseReadinessRecord({
  generatedDate,
  sourceMarkdownPath,
  readinessMarkdown,
}) {
  return [
    `# 真实案例就绪度_${generatedDate}`,
    "",
    "> 生成方式：代码侧 `report:real-case-readiness` + `export:obsidian-readiness` 自动生成草稿",
    `> 生成日期：${generatedDate}`,
    `> 对应代码报告：${sourceMarkdownPath}`,
    "> 文档状态：可继续编辑",
    "",
    "## 0. 使用说明",
    "- 这是一份真实案例回填就绪度草稿，用来判断每条 real-case 还缺什么。",
    "- 下面的“代码侧就绪度底稿”来自当前代码报告。",
    "- 你后续应继续补：优先级判断、先回填哪条、为什么。",
    "",
    "## 1. 代码侧就绪度底稿",
    "",
    readinessMarkdown.trim(),
    "",
    "## 2. 人工判断",
    "- 当前最值得优先补完的案例：",
    "- 当前最卡的缺失字段：",
    "- 哪类缺失说明模板还不够好：",
    "",
    "## 3. 下一批动作",
    "- [ ] 下一条先补哪一项：",
    "- [ ] 下一次要跑的命令：",
    "- [ ] 是否需要补模板或字段：",
    "",
  ].join("\n");
}
